name: CDN

on:
  push:
    branches:
      - main

jobs:
  build-cdn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/dtalabs/cdn:latest
          provenance: false

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io

  deploy-cdn:
    needs: build-cdn
    secrets: inherit
    uses: dtalabs/ci-cd/.github/workflows/helm-deployment.yaml@main
    with:
      helm_chart_dir: 'add-ons/cdn'
      namespace: 'dtalabs'
      values_file: 'prod.values.yaml'
      deployment_name: 'cdn'
